### ISSUE TITLE
QXcbConnection: XCB error:

### ISSUE THREAD

**Issue by XuankeShi** [Elena-ssq/frustum-pointnets-view-results#1]
I have put it in the right place，but when i run the ‘’python kitti/view_results.py‘’ ，the error occurs and i don’t know why，The error message is as follows：
python kitti/view_results.py

Type, truncation, occlusion, alpha: Cyclist, -1, -1, -10.000000
2d bbox (x0,y0,x1,y1): 677.000000, 165.000000, 689.000000, 191.000000
3d bbox h,w,l: 1.690468, 0.401733, 1.763962
3d bbox location, ry: (4.661238, 1.029085, 45.946292), -1.732423
('Image shape: ', (375, 1242, 3))
('pts_3d_extend shape: ', (8, 4))
QXcbConnection: XCB error: 145 (Unknown), sequence: 171, resource id: 0, major code: 139 (Unknown), minor code: 20

**Comment by Elena-ssq** [comment]
Hi,

I'm not sure why this happens, but checking the following items might help:

- First, check if kitti_objects runs correctly;
- If so, check if you change all paths in `view_results.py` according to your condition;
- If not, there may be some thing wrong with your frustum settings.

Wish this helps.

**Comment by loneclown** [comment]
Hello,

when i use the code,shou i download the kitti dataset,.
when i just use the prepared data,it show me :
    Traceback (most recent call last):
  File "kitti/view_results.py", line 235, in <module>
    dataset_viz()
  File "kitti/view_results.py", line 214, in dataset_viz
    objects = dataset.get_label_objects(data_idx)
  File "kitti/view_results.py", line 70, in get_label_objects
    assert(idx<self.num_samples and self.split=='training')
AssertionError

what can i do for that,thank you.
